-- 코드를 작성해주세요
SELECT E.ID, COALESCE(C.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (
    SELECT 
        PARENT_ID,
        COUNT(*) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
    ) C
ON E.ID = C.PARENT_ID
ORDER BY E.ID