-- 코드를 입력하세요
SELECT p.PRODUCT_CODE AS PRODUCT_CODE, sum(o.SALES_AMOUNT * p.PRICE) AS SALES
from OFFLINE_SALE o join PRODUCT p on (p.PRODUCT_ID = o.PRODUCT_ID)
group by PRODUCT_CODE
order by SALES desc, PRODUCT_CODE;