-- 코드를 입력하세요
SELECT CAR_ID, round(abs(avg(DATEDIFF(END_DATE, START_DATE) + 1)), 1) AS AVERAGE_DURATION
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having abs(avg(DATEDIFF(END_DATE, START_DATE) + 1)) >= 7
order by AVERAGE_DURATION desc, CAR_ID desc;