-- 코드를 작성해주세요
SELECT 
    CASE 
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 and 3 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 and 6 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 and 9 THEN '3Q'
        ELSE '4Q'
    END AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;