-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF f
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) j ON f.FLAVOR = j.FLAVOR
ORDER BY f.TOTAL_ORDER + IFNULL(j.JULY_ORDER, 0) DESC
LIMIT 3;