-- 코드를 입력하세요
WITH MAX_REVIEWER AS (
    SELECT P.MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM MEMBER_PROFILE P JOIN REST_REVIEW R ON (P.MEMBER_ID = R.MEMBER_ID)
    GROUP BY P.MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P 
    JOIN REST_REVIEW R ON (P.MEMBER_ID = R.MEMBER_ID)
    JOIN MAX_REVIEWER M ON (P.MEMBER_ID = M.MEMBER_ID)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;