SELECT 
    MONTH(h.START_DATE) AS MONTH,
    h.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) eligible
ON h.CAR_ID = eligible.CAR_ID
WHERE h.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(h.START_DATE), h.CAR_ID
ORDER BY MONTH, h.CAR_ID DESC;